### ISSUE TITLE
Add scale subresource to CRD

### ISSUE THREAD

**Issue by HarryGogonis** [evryfs/github-actions-runner-operator#100]
I believe this is necessary to use a VPA on the GithubActionRunner
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource

**Comment by davidkarlsen** [comment]
The controller simply spawns pods

**Comment by HarryGogonis** [comment]
> The controller simply spawns pods

can the controller expose # of replicas?

**Comment by davidkarlsen** [comment]
yes, current number of pods is shown when you do k get githubactionrunner <therunner>
