### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by jcputter** [evryfs/github-actions-runner-operator#105]
Hi,

I followed the instructions, installed the chart and I have the operator pod running however i'm trying to get the pool runners to work. I looked at https://github.com/evryfs/github-actions-runner-operator/blob/master/config/samples/garo_v1alpha1_githubactionrunner.yaml but after applying the manifest i dont see the runner pod getting launched?

Maybe some additional docs?

**Comment by davidkarlsen** [comment]
What does the logs of the controller say?

**Comment by jcputter** [comment]
`2020-09-30T09:01:18.943Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "garo.tietoevry.com", "reconcilerKind": "GithubActionRunner", "controller": "githubactionrunner", "name": "runner-pool", "namespace": "github-actions-runner-operator", "error": "Secret \"actions-runner\" not found"}
`
Thanks, i see now its missing a secret, what gets stored in the secret? what is the key/value?

**Comment by davidkarlsen** [comment]
It is specified at:
https://github.com/evryfs/github-actions-runner-operator/blob/master/config/samples/garo_v1alpha1_githubactionrunner.yaml#L17
and passed to the runner container at: https://github.com/evryfs/github-actions-runner-operator/blob/master/config/samples/garo_v1alpha1_githubactionrunner.yaml#L56

The value is a token that has scope to de/register runners.

**Comment by jcputter** [comment]
ah thanks that makes sense. I now get this. I double checked for whitespace in the base64 

`2020-09-30T10:53:19.087Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "garo.tietoevry.com", "reconcilerKind": "GithubActionRunner", "controller": "githubactionrunner", "name": "runner-pool", "namespace": "github-actions-runner-operator", "error": "Get \"https://api.github.com/orgs/travelstart/actions/runners?per_page=30\": net/http: invalid header field value \"Bearer xxxxxxxxxxxx\\n\" for key Authorization"}
`

**Comment by jcputter** [comment]
I am using a personal token

**Comment by davidkarlsen** [comment]
it should just be the value, not prefixed with Bearer.

**Comment by jcputter** [comment]
Awesome thanks that worked

Can you explain the configmap for me https://github.com/evryfs/github-actions-runner-operator/blob/092f156aeecc428b738ad9bfd943bcd5790c897c/config/samples/garo_v1alpha1_githubactionrunner.yaml#L119

I can see that the runner-pod is launching but its failing because it cannot mount the volume

`MountVolume.SetUp failed for volume "settings-xml" : configmap "settings-xml" not found`

I have a configmap but the k/v is empty

Thanks

**Comment by jcputter** [comment]
Nevermind, i see its for maven config. Thanks for all your help

**Comment by stewartbryson** [comment]
> Nevermind, i see its for maven config. Thanks for all your help

@jcputter I'm seeing this error message as well. What is the solution?

Thank you.
