### ISSUE TITLE
Add to documentation if runners are "throw away" / "single use"

### ISSUE THREAD

**Issue by mithro** [evryfs/github-actions-runner-operator#123]
This project looks super interesting but I had one question, are the runners thrown away after they run a single job? 

According to https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories;
> We recommend that you do not use self-hosted runners with public repositories.
> 
> Forks of your public repository can potentially run dangerous code on your self-hosted runner machine by creating a pull request that executes the code in a workflow.
>
> This is not an issue with GitHub-hosted runners because each GitHub-hosted runner is always a clean isolated virtual machine, and it is destroyed at the end of the job execution.

It would be good if the documentation explicitly stated if it behaves (or can be configured to behave) like the GitHub-hosted runners were the runner is thrown away after a single use.

Thanks for your awesome work!

**Comment by davidkarlsen** [comment]
See https://github.com/actions/runner/issues/510 for this feature.
You can try enabling it with an env-var like:
```
- name: ACTIONS_RUNNER_INPUT_ONCE
  value: "true"
```

**Comment by davidkarlsen** [comment]
@mithro did it work out for you?

**Comment by mithro** [comment]
@davidkarlsen - Haven't had a chance to test it yet. Probably be a week or two before we get it going.

**Comment by heilerich** [comment]
The solution suggested in @davidkarlsen 's [comment](https://github.com/evryfs/github-actions-runner-operator/issues/123#issuecomment-739487280) works perfectly for me.

I can't reopen this issue, but I think this should go into the documentation somewhere.

Great project!
