### ISSUE TITLE
How to restart crd/pods?

### ISSUE THREAD

**Issue by pcm32** [evryfs/github-actions-runner-operator#128]
Hi!

We recently needed to update the container for the runner. After pushing that container and editing our crd.yaml for the runner-pool (and applying the change with `kubectl apply -f crd.yml`, the new pod with new update config wouldn't come up after deleting the previously existing pod with `kubectl delete pod/<runner-pod-name>`.

I tried then to delete the crd from k8s and re-create it (with `kubectl delete -f crd.yml` and `kubectl create -f crd.yml`), however now I see:

```
$ kubectl get GithubActionRunner/runner-pool
NAME          CURRENTPOOLSIZE
runner-pool
```

(it used to say 1)

and no pod starts. Any ideas of how I should go around this process of updating? Thanks!

**Comment by pcm32** [comment]
I see this in the log of the operator pod:

```
2020-12-18T00:34:01.854Z	INFO	controllers.GithubActionRunner	Reconciling GithubActionRunner	{"githubactionrunner": "default/runner-pool"}
2020-12-18T00:34:02.208Z	INFO	controllers.GithubActionRunner	Pods and runner API not in sync, returning early	{"githubactionrunner": "default/runner-pool"}
```

**Comment by davidkarlsen** [comment]
If u delete the pod the updated resource will be applied (technically it is not the CRD per se, but a resource specified by the CRD - a CR). https://github.com/evryfs/github-actions-runner-operator/issues/22 touches into this. As pods get old and cycle the new definition will take place. https://github.com/evryfs/github-actions-runner-operator/issues/86 also touches into this, as a policy could be implemented to sort which pods to delete 1st (the oldest or newest ones, being idle).

**Comment by pcm32** [comment]
Thanks @davidkarlsen. I could make it work by deleting with `kubectl delete GithubActionRunner/runner-pool` and then changing the name in the crd.yaml for the `GithubActionRunner` (say, runner-pool-2) and re-applying that worked. But apparently something was left in some stale state associated to that initial name after the deletes.

**Comment by davidkarlsen** [comment]
Another option is to just delete the idle runners, which will make the operator pick up the new definition. Deleting the whole pool will of course also end in runners being redefined and pick up your reconfig.

**Comment by davidkarlsen** [comment]
Feel free to close if you are happy with the answers.
