### ISSUE TITLE
GitHub Enterprise

### ISSUE THREAD

**Issue by iptizer** [evryfs/github-actions-runner-operator#175]
Does github-actions-runner-operator support "GitHub Enterprise"?

I can't find configuration options to set the API URL, niether on CR level, nor in the Helm chart. So presumeably this is not supported?

**Comment by davidkarlsen** [comment]
As in github-enterprise *server* ? Not atm, but this should be possible quite easily. I however do not have a test-environment. I could create a branch which you can test?

**Comment by davidkarlsen** [comment]
Actually, try this:

```yaml
env:
- name: GITHUB_APP_V3APIURL
  value: https://api.yourinstance.com
- name: GITHUB_APP_V4APIURL
  value: https://api.yourinstance.com
```

and it should be picked up.

if it works I can fix the chart to support it ootb.

**Comment by davidkarlsen** [comment]
Did that work @iptizer ?

**Comment by davidkarlsen** [comment]
@iptizer would love any feedback, positive or negative, or even a "I don't have time" - just to be able to navigate these waters.

**Comment by iptizer** [comment]
@davidkarlsen Thanks for your quick feedback! I will try out these variables in my next time slice dedicated to GitHub actions. Give me a week or so :). Sorry it is currently only a side project of mine.

**Comment by iptizer** [comment]
Just wanted to let you know => Still on it.

Just GHA in Enterprise Server is still in development and currently the endpoints are not even available. I'll let you know as soon as those are available.

**Comment by davidkarlsen** [comment]
Thanks for the feedback - was just about to ping you. Are you on the latest release? Can you tell which endpoints are/are not available?

**Comment by ivo4311** [comment]
Just tested this on a GitHub Enterprise. Here's what I found:

- Changing the GitHub API URL for the operator is possible via the env (so long as you use the correct env variable names [as seen in the code](https://github.com/palantir/go-githubapp/blob/develop/githubapp/config.go#L44)

```yaml
- name: GITHUB_V3_API_URL
  value: https://api.yourinstance.com
- name: GITHUB_V4_API_URL
  value: https://api.yourinstance.com
```
- When the containers for the pods are being created the runner fails with the following error:
```console
Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Response status code does not indicate success: 404 ().
```
> Note: I set the same env variables on the runner container and operator. I don't know if the runner uses the same package (or anything of what it uses under the hood) but decided to test it just in case.

Needless to say `https://api.github.com` is not the api url I had configured in the env. I suspect [this](https://github.com/evryfs/github-actions-runner/blob/master/entrypoint.sh#L10) may be the issue though I haven't investigated at length. I'll try and get back to it next week if I have the time.

**Comment by davidkarlsen** [comment]
Great - that's what I expected.
Then I can make this more configurable through the helm-chart.

As for the runners that's an issue that should be registered for https://github.com/evryfs/github-actions-runner

**Comment by ivo4311** [comment]
Thanks. I'll open an issue on that repo then.

Have a good day!

**Comment by davidkarlsen** [comment]
thanks for reporting!

**Comment by davidkarlsen** [comment]
https://github.com/evryfs/github-actions-runner/pull/45 and https://github.com/evryfs/helm-charts/pull/50 should make this possible in an easy way.
