### ISSUE TITLE
Regtoken copies labels from GithubActionRunner which does not play nicely with fluxcd 

### ISSUE THREAD

**Issue by mrGrazy** [evryfs/github-actions-runner-operator#193]
https://github.com/evryfs/github-actions-runner-operator/blob/2067ceba829cb64dcd8dff30727e619e723a01b7/controllers/githubactionrunner_controller.go#L278

When a new regtoken is created, the labels from the GithubActionRunner are copied onto the regtoken. 
Our cluster uses fluxcd to apply changes to the cluster. FluxCD labels object it has created so it can reconcile deletions later. When these labels are copied onto the secret, fluxCD assumes that it is managing the secret (rather than the garo operator) and tears it down again. 

This isn't actually causing us any issues because we're not yet using the regtoken, but it makes it unusable for now.

**Suggestion:**
If copying the labels is important, it would be helpful if there was some kind of configurable white/blacklist.

**Comment by mrGrazy** [comment]
This is potentially an issue for more than FluxCD. As far as I understand, it is common for labels to be used by many k8s subsystems to add behaviours that might not make sense to copy from one object to another. (I think helm also does this)

**Comment by davidkarlsen** [comment]
In your case it would work out anyway, as deleting the CR would make the regtoken an orphan which would delete it anyways. But I agree that it is not a good practice, and we now only propagate relevant labels.
