### ISSUE TITLE
implement scaling based on runner demand

### ISSUE THREAD

**Issue by davidkarlsen** [evryfs/github-actions-runner-operator#2]
If GH apis will expose if runner is queued with a job or idle (as it is in the UI), scaling can properly implemented to satisfy demand within limits defined in the CR.

**Comment by davidkarlsen** [comment]
Blocking issue: https://github.com/actions/runner/issues/454

**Comment by iagomelanias** [comment]
Hello! 👋 
Thank you for creating this operator. It's going to help a lot!

I have a question: what's the current behavior?
Is there any scaling at all or should we set `minReplicas` and `maxReplicas` to the same value?

**Comment by davidkarlsen** [comment]
No scaling for the time being as the API needs to be updated as in the linked issue. If you set min==max it will create that number of runners.

**Comment by davidkarlsen** [comment]
Related: https://github.com/google/go-github/issues/1589

**Comment by davidkarlsen** [comment]
@iagomelanias Latest v0.3.0 now supports autoscaling! Please give it a spin.
