### ISSUE TITLE
spec.podTemplateSpec.metadata is not persisted

### ISSUE THREAD

**Issue by ekarlso** [evryfs/github-actions-runner-operator#204]
When you create a GAR instance the podTemplateSpec.metadata is {}, it seems there's some controller code / CRD code that is not working properly.

https://github.com/kubernetes-sigs/controller-tools/issues/448
https://github.com/minio/operator/pull/423/files
https://github.com/kubernetes-sigs/controller-tools/pull/539

**Comment by davidkarlsen** [comment]
Related https://github.com/evryfs/github-actions-runner-operator/pull/203

**Comment by AmitBenAmi** [comment]
I saw that the tests should cover the error, but it still happens on my environment using the latest version (as stated in #233), with PR #221 
Is it something caused by `kubebuilder`, or is it something specific in the controller of this operator?
