### ISSUE TITLE
support for persistent volumes?

### ISSUE THREAD

**Issue by robwhitby** [evryfs/github-actions-runner-operator#211]
Hi,

We would like use a persistent volume for `/var/lib/docker` instead of using an `emptyDir`. Most of our jobs pull the same docker images so it would be much faster if each task didn't start with an empty cache.

Is this possible at the moment? From our understanding it seems the `podTemplateSpec` has to refer to a specific volume claim, unlike, for example, a `StatefulSet` which allows dynamic volumes with `volumeClaimTemplates`.

Thanks!

**Comment by davidkarlsen** [comment]
No, that is not currently supported. Maybe you can use an init-container?

**Comment by simonjohansson** [comment]
We are new to all of this k8s stuff. :) Could you explain what we could do in the init-container? Our understanding is that the init-container is launched before any other containers in the pod. But the pod spec has already been defined in the `GithubActionRunner`.

**Comment by davidkarlsen** [comment]
the init will run before the main containers, so that you could seed any data via the init - but I am unsure how much value it would bring.

**Comment by fbuinosquy1985** [comment]
this is a good feature that should be supported if is is possible .
