### ISSUE TITLE
Operator doesn't respond to `Evicted` runner

### ISSUE THREAD

**Issue by FrederikNS** [evryfs/github-actions-runner-operator#232]
We frequently experience runners getting evicted, due to using too much ephemeral storage. It's probably due to the builds themselves not cleaning up after themselves.

However when a runner is evicted due to using too much memory or ephemeral storage, nothing happens. I can see a use for keeping the Evicted pod around for debugging purposes, but the operator should notice that a runner was evicted, and spin up a new one, to ensure that the minimum number of healthy runners is kept around. If the Evicted pod is deleted, the operator responds immediately by spinning up a new runner.

Would it be possible for the operator to regard an Evicted runner just like if it doesn't exist?

**Comment by yfried** [comment]
We see the same problem

**Comment by davidkarlsen** [comment]
thanks for reporting, can you check if the runners are still registered at github when the pod has been evicted (needs to be checked quite soon after it becoming evicted, as gh will eventually remove dead runners). Some logic may be needed to get them unregistered, as well as catering for the pod-status.

**Comment by yfried** [comment]
> thanks for reporting, can you check if the runners are still registered at github when the pod has been evicted (needs to be checked quite soon after it becoming evicted, as gh will eventually remove dead runners). Some logic may be needed to get them unregistered, as well as catering for the pod-status.

@davidkarlsen 
1. Yes - Evicted pods are still registered at github (Org Settigns -> Actions -> Self-hosted runners -> Runner groups)
2. They are left there for a while. We had one stuck in Offline for the whole weekend

**Comment by duyhenryer** [comment]
I the same problem.

**Comment by davidkarlsen** [comment]
1. what version are you running?
2. what does the operator logs say? (It should attempt to deregister them with gh and then remove the finalizer, allowing them to be deleted.

**Comment by duyhenryer** [comment]
@davidkarlsen OK Bro, 
I had stuck same issues [212](https://github.com/evryfs/github-actions-runner-operator/issues/212#issue-829558895) here, I start the latest version and another namespace. I check Evicted pods is deleted.
But namespace old it still status `Terminating`.
Thank bro

**Comment by Yagyansh** [comment]
@davidkarlsen 
I am still facing this issue in v0.10.0. New runner pods don't come up when an older pod gets evicted and then that runner pool goes out of sync and all the jobs get queued.

**Comment by Yagyansh** [comment]
@davidkarlsen Any insights?
