### ISSUE TITLE
latest image is not always pulled

### ISSUE THREAD

**Issue by Anusha-Kolli** [evryfs/github-actions-runner-operator#243]
The GH Runner is set to use the "latest" tag so that it's always up-to-date. However, if this image tag is cached on the node, it will not pull the latest image. The pod will subsequently CrashLoop with:
```sh
2021-05-10 15:41:24Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.278.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should back online within 10 seconds.
```

**Comment by davidkarlsen** [comment]
You control this with the `imagePullPolicy`(https://github.com/evryfs/github-actions-runner-operator/blob/master/config/samples/garo_v1alpha1_githubactionrunner.yaml#L63)
