### ISSUE TITLE
NotFound from 'POST https://api.github.com/actions/runner-registration'

### ISSUE THREAD

**Issue by MPV** [evryfs/github-actions-runner-operator#30]
Trying out org runners, but the pods crash-loop with:

```
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
Response status code does not indicate success: 404 (Not Found).
```

Things we've done:
- Installed the chart (no custom values)
- Added a `github-token` secret with token with `admin:org` access as `GH_TOKEN` key
- Added the `GitHubActionRunner` from the README (but adapted `organization` and removed unused `settings-xml`).

**Comment by davidkarlsen** [comment]
Fixed by #29

**Comment by davidkarlsen** [comment]
I have also been contemplating if this secret should rather be with the operator, so that the operator can run in it's own namespace along-side the secret (which has quite high permissions), so that it can create the shorter lived registration-tokens (which has lower permissions) in the namespace where the actual runners will run.

Any thoughts on this?

**Comment by Fresheyeball** [comment]
See this again here.

**Comment by davidkarlsen** [comment]
@Fresheyeball please open a new ticket with debug info.
