### ISSUE TITLE
Docker credentials

### ISSUE THREAD

**Issue by sr-apotapov** [evryfs/github-actions-runner-operator#308]
Hi!
Not sure if that's qualifies as an issue...
The question is pretty simple - is there an easy way to provide credentials for runner for pulling images from the `docker hub` and private registries? 
It's pretty huge deal, especially for organizations.

**Comment by davidkarlsen** [comment]
yes, just define them under `spec.podTemplateSpec.spec.containers` as usual.

**Comment by davidkarlsen** [comment]
Feel free to reopen if any further clarification is needed.

**Comment by sr-apotapov** [comment]
Hey, thanks for quick response. 
Probably I'm bad at explanation. By pulling I meant not the images **for** the runner\metric\dind containers, but pulling **by** the runner itself.
In our github actions workflows we're using a lot of containers for the workflow itself (for example `ghcr.io/github/super-linter:v3.17.1` for CI).
And I was wondering how to pull all of those images from the private registries?

**Comment by davidkarlsen** [comment]
You then need to do a `docker login` to define the credentials.
