### ISSUE TITLE
Runner Groups

### ISSUE THREAD

**Issue by brian-pickens** [evryfs/github-actions-runner-operator#312]
Is there a way to specify the runner group(s) for the runners to attach to?

**Comment by davidkarlsen** [comment]
Try setting a variable `ACTIONS_RUNNER_INPUT_RUNNERGROUP` to the desired group. Does that work?

**Comment by davidkarlsen** [comment]
If it works, this could be documented in the example @Otterian

**Comment by brian-pickens** [comment]
Where would this variable go?

**Comment by davidkarlsen** [comment]
In the runner pod

**Comment by davidkarlsen** [comment]
@brian-pickens did it work?

**Comment by davidkarlsen** [comment]
Closing due to lack of feedback
