### ISSUE TITLE
It's possible change the autoscaling parameters?

### ISSUE THREAD

**Issue by santos-edu** [evryfs/github-actions-runner-operator#319]
It's working fine, thanks for the great work.
I would like to know if it is possible to change the autoscaling parameters so that new pods are created faster and in more quantity.
Example, today in an action that I have 8 jobs to run, the operator scaling just one more pod for execution.

**Comment by davidkarlsen** [comment]
You can reduce the reconciliationPeriod which will make it reconcile more frequently, you can increase the TTL which will make runners stick around for longer periods to pick jobs.

**Comment by santos-edu** [comment]
@davidkarlsen  tks, I couldn't find the TTL parameter. But reconciliationPeriod help me.
tks
