### ISSUE TITLE
Metrics for monitoring the operator

### ISSUE THREAD

**Issue by MPV** [evryfs/github-actions-runner-operator#34]
Are there any metrics exposed for monitoring the operator?

I see `kube-metrics`/`metrics` from the `operator-framework` being used for registering a ServiceMonitor for the operator, but I haven't yet found if there's any metrics being exposed?

https://github.com/evryfs/github-actions-runner-operator/blob/master/cmd/manager/main.go

![Skärmavbild 2020-06-10 kl  08 44 14](https://user-images.githubusercontent.com/62675/84235827-cdd22700-aaf6-11ea-8fd0-fb257e7c4531.png)

**Comment by MPV** [comment]
Sorry, I didn't follow, what's the behaviour now after the fix?

**Comment by davidkarlsen** [comment]
The operator creates the service, but the created service used a `name: operatorname` label in the selectors (which did not match the ones used in the chart) hence they did not match. Now they do.
`curl <operatorname>.svc:8383/metrics` and `curl <operatorname>.svc:8686/metrics` should now return metrics.

**Comment by MPV** [comment]
Nice, thanks!

Which metrics are there at the moment?
