### ISSUE TITLE
A runner exists with the same name

### ISSUE THREAD

**Issue by mattkim** [evryfs/github-actions-runner-operator#368]
Hi, we've been using this operator for a while now and it usually works great but sometimes the operator gets stuck.

In this case we get the error:

> A runner exists with the same name

I'm not sure how it gets into this state, but it seems that when runners are idle for a while the operator seems to try and restart them, and isn't aware that the id is already registered.

Is there a way to mitigate this issue? Could the operator just remove the duplicate runner in this case?

**Comment by davidkarlsen** [comment]
@mattkim which version of the runner image do you use? Where do you see this message?
Maybe it was fixed by https://github.com/evryfs/github-actions-runner/commit/8bb89e3b6e0919d3255b112e5830691225c395f8 ?

**Comment by mattkim** [comment]
We are running v0.9.3, I'll try updating to the latest version and see if that helps, thanks!

**Comment by davidkarlsen** [comment]
Closing due to lack of feedback.
