### ISSUE TITLE
Pods and runner API not in sync, returning early

### ISSUE THREAD

**Issue by mattkim** [evryfs/github-actions-runner-operator#369]
Hello again,

We've also noticed that every now and then we are getting this error from the operator.

> Pods and runner API not in sync, returning early

It seems that this happens when there is a runner in the github repo with no corresponding pod.

Not sure how we get into this state, but is it possible to have the operator just automatically remove the unknown runner to keep the "pods and runner api" in sync?

**Comment by davidkarlsen** [comment]
@mattkin this can happen in the [short] timeframe where pods have been spawned but not yet registered with github, it should fix it self after the pods have started and registered.

**Comment by mattkim** [comment]
Hi @davidkarlsen thanks for the response

Is it possible to get in a state where the pod has registered the runner name with github, crashes and on retry sees a duplicate runner with the same name?

I think this is one use-case we have observed.

**Comment by brian-pickens** [comment]
Any tips for debugging why a runner isn't starting up? I'm not seeing any logs in the operator that could be indicating a problem.

**Comment by davidkarlsen** [comment]
> Any tips for debugging why a runner isn't starting up? I'm not seeing any logs in the operator that could be indicating a problem.

See operator log. Also try describe on the runner pod and check its log

**Comment by ckittelmann** [comment]
I'm faced with the same problem. After many weeks of running nice and smoothly a runner is not removed by the operator in the github runner api and from this point the scaling of runners is not working anymore and I continuously getting this error in the log until I remove this runner by hand. 
Any advise or sth. that I can do to solve/finding this?

**Comment by davidkarlsen** [comment]
Check the list of runners at github and forcefully delete them if malfunctioning
