### ISSUE TITLE
Register runners on repo

### ISSUE THREAD

**Issue by RomainBelorgey** [evryfs/github-actions-runner-operator#40]
Great project, but it looks like it is working only when registering runners to an org.

Can it be possible to register them by repository ?

**Comment by davidkarlsen** [comment]
That should not be to hard to do. Do you want to provide a PR?

**Comment by RomainBelorgey** [comment]
Oh thanks for the quick commit. Sorry I was late to answer ... :(
And I was not expecting for it to be so easy :sweat_smile:
