### ISSUE TITLE
failed to solve with frontend dockerfile.v0:  failed to create LLB definition:

### ISSUE THREAD

**Issue by Sandeepb-nextcar** [evryfs/github-actions-runner-operator#426]
failed to solve with frontend dockerfile.v0: failed to create LLB definition: Dockerfile parse error line 15: Unknown flag: mount

I'm able to create opeartor and runner successfully, however runner is having issue while build the docker image with above error, i suspect it to be version issue. I see runners are having docker 19.03 version how can i get v 20.10.8 ?

**Comment by davidkarlsen** [comment]
Your Dockerfile frontend does not match your docker version.
This is not related to the operator, but rather https://github.com/evryfs/github-actions-runner, or the docker sidecar: https://github.com/evryfs/github-actions-runner-operator/blob/master/config/samples/garo_v1alpha1_githubactionrunner.yaml#L79
