### ISSUE TITLE
Operator doesn't delete Evicted Pods.

### ISSUE THREAD

**Issue by Yagyansh** [evryfs/github-actions-runner-operator#464]
Operator Version - v0.10.0

I'm using GHE.

When pods for a runner pool evict, the pods are successfully unregistered from Github but the pods aren't deleted and new pods aren't spun which leads to jobs being queued.
If I have 1 runner pod which gets evicted, then the CURRENTPOOLSIZE for the runner pool remains 1 which is why no new pod is spun.

I've already seen https://github.com/evryfs/github-actions-runner-operator/issues/232. This solves the evicted runners being unregistered, which is happening successfully but pods aren't being deleted.

**Comment by davidkarlsen** [comment]
@Yagyansh Evicted pods are a sign of something malfunctioning, hence k8s does not remove them automatically (in order to let the user detect the fact and understand why).

What does the logs of the operator say?

**Comment by Yagyansh** [comment]
@davidkarlsen 

I understand that, but when the operator has successfully de-registered the pod why isn't a new pod(i.e runner) being created?

I don't see any errors when the operator unregister the evicted pod.

Should the evicted pods be handled gracefully by the operator after Also, if eviction is not handled gracefully then what exactly https://github.com/evryfs/github-actions-runner-operator/issues/232's fix?

**Comment by Yagyansh** [comment]
Also, I do see util.api ERROR sometimes, but I don't think it has anything to do with Eviction case.

`github-actions-runner-operator 2022-08-02T17:05:21.147Z	ERROR	util.api	unable to update status	{"error": "Operation cannot be fulfilled on githubactionrunners.garo.tietoevry.com \"<runner-gar-name>\": the object has been modified; please apply your changes to the latest version and try again"}

github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator github.com/evryfs/github-actions-runner-operator/controllers.(*GithubActionRunnerReconciler).manageOutcome
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator 	/workspace/controllers/githubactionrunner_controller.go:181
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator github.com/evryfs/github-actions-runner-operator/controllers.(*GithubActionRunnerReconciler).handleScaling
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator 	/workspace/controllers/githubactionrunner_controller.go:122
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator github.com/evryfs/github-actions-runner-operator/controllers.(*GithubActionRunnerReconciler).Reconcile
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator 	/workspace/controllers/githubactionrunner_controller.go:97
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:114
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:311
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator 2022-08-02T17:05:21.147Z	ERROR	controller.githubactionrunner	Reconciler error	{"reconciler group": "garo.tietoevry.com", "reconciler kind": "GithubActionRunner", "name": "navi-sa-runner-pool", "namespace": "infrastructure", "error": "Operation cannot be fulfilled on githubactionrunners.garo.tietoevry.com \"navi-sa-runner-pool\": the object has been modified; please apply your changes to the latest version and try again"}
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
github-actions-runner-operator-747bfc8dc5-422gj github-actions-runner-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227
`
