### ISSUE TITLE
Multi-arch support (arm64)

### ISSUE THREAD

**Issue by samip5** [evryfs/github-actions-runner-operator#468]
Hi,

I would love to use this, but unfortunately all of the container images used are x86_64 only, so that results in exec format error on some of my nodes and I would want to do arm64 runner jobs.

**Comment by davidkarlsen** [comment]
@samip5 Is it the actual runner image: https://github.com/evryfs/github-actions-runner you want to run on arm, or the operator (this repo) itself?

**Comment by samip5** [comment]
> @samip5 Is it the actual runner image: https://github.com/evryfs/github-actions-runner you want to run on arm, or the operator (this repo) itself?
> 

I would like to run both.

**Comment by davidkarlsen** [comment]
this was afair solved in the runner image repo
