### ISSUE TITLE
401 Bad credentials

### ISSUE THREAD

**Issue by aqabawe** [evryfs/github-actions-runner-operator#54]
I'm getting this error
```
"error":"GET https://api.github.com/orgs/OrgName/actions/runners?per_page=30: 401 Bad credentials []"
```
Does this mean there's something wrong with the secret definition? I am using the token you get from `https://github.com/organizations/OrgName/settings/actions/add-new-runner`

**Comment by aqabawe** [comment]
Using a personal token worked.

**Comment by davidkarlsen** [comment]
Yes, you need to use a long-lived token, as the registration tokens are short-lived and issued by the runner container: https://github.com/evryfs/github-actions-runner/blob/master/entrypoint.sh
