### ISSUE TITLE
Official support for the latest version of k8s

### ISSUE THREAD

**Issue by kamil-branch** [evryfs/github-actions-runner-operator#578]
@davidkarlsen `github-actions-runner-operator` is widely used by many end users. The latest release of `github-actions-runner-operator` was made in November 2022. In the release notes we can see that it supports officially k8s 1.24 -> https://github.com/evryfs/github-actions-runner-operator/blob/v0.11.0/.github/workflows/build.yaml#L47
On the master branch there is a support for 1.26 but changes are not released -> https://github.com/evryfs/github-actions-runner-operator/blob/master/.github/workflows/build.yaml#L47
Latest k8s release is 1.28 and most of the cloud providers like AWS, Google etc provides support for k8s 1.27+. Additionally cloud providers require regular cluster upgrades. Could you release the new version of `github-actions-runner-operator` which officially supports k8s 1.27+? 
Updating matrix compatibility of `github-actions-runner-operator` will help a lot all of the users with regular k8s upgrades.

**Comment by davidkarlsen** [comment]
@kamil-branch Unfortunately I no longer have commit-rights to the repo as I've switched jobs.
Maybe @otterian can make me a contributor? That said the operator should work just fine on newer k8s versions too as it uses the stable versions - nevertheless it would be good to update the libraries in use and verify on newer k8s versions.
Keep in mind though that I don't have access to a k8s cluster connected to a gh-org for testing.

**Comment by kriberg** [comment]
@davidkarlsen: should've been sorted now.

**Comment by davidkarlsen** [comment]
@kamil-branch @otterian @kriberg 
Can you try quay.io/evryfs/github-actions-runner-operator:v0.11.0-29-gbb4b3c3 and also let me know the k8s version you tested on? As it passes in CI which tests on `v1.26.6` and `v1.28.0` and passes I expect it to be smooth sailing.

If so I can create a release.

**Comment by davidkarlsen** [comment]
@kamil-branch ? @Otterian?

**Comment by kamil-branch** [comment]
Thanks for these changes David! Will make some tests tomorrow

**Comment by davidkarlsen** [comment]
Thanks. Released as v0.11.1: https://github.com/evryfs/github-actions-runner-operator/releases/tag/v0.11.1 - Chart in https://github.com/evryfs/helm-charts baking now.
