### ISSUE TITLE
Add defaults to CRD

### ISSUE THREAD

**Issue by davidkarlsen** [evryfs/github-actions-runner-operator#69]
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting - when moving to apiextensions.k8s.io/v1 also add defaults for:
* reconciliationPeriod (1m)
* minRunners (1)
* maxRunners (1)

**Comment by RichiCoder1** [comment]
Per this, how much of the pod spec template is required?

**Comment by davidkarlsen** [comment]
Not sure I follow? Do you mean how much is required to be defined as of today?
if so, min and max.

**Comment by RichiCoder1** [comment]
> Not sure I follow? Do you mean how much is required to be defined as of today?
if so, min and max.

Exactly. Good to know, the example just makes it seem as if everything is required at this second. Ty!

**Comment by davidkarlsen** [comment]
Thanks, added docs in https://github.com/evryfs/github-actions-runner-operator/commit/7c66110723c6e13a68e87eab7883cdaa1541eb5c
