### ISSUE TITLE
Scale runners to 0?

### ISSUE THREAD

**Issue by andypanix** [evryfs/github-actions-runner-operator#81]
Hi @davidkarlsen thanks for the great job ;) 

I'm looking for a solution to a problem that may not be so rare.

On our clusters we have dedicated nodes (high performance and therefore high cost) on which to run build runners  (we call them build-pools). When not needed, nodes must be able to scale to zero, and this is a requirement.

This is simple if there are no runner pods running (e.g. at night), however in the case of a GithubActionRunner, the fact that there must always be at least one up-and-running pod prevents nodes from scaling to zero, always leaving at least one.

We tried to think of some solution but we couldn't find an "elegant" way to solve the problem.

Is there any way to scale the runners to 0? 

Or alternatively assign only the first always-up runner to a different node pool? Although not optimal, it could be an acceptable compromise.

Thanks!

**Comment by davidkarlsen** [comment]
The problem with that is that w/o any active runners any jobs that attempt scheduling will fail.
In contrast when you have one runner (even if occupied) the second job will sit in status `queued`.

**Comment by davidkarlsen** [comment]
Closing since it is not possible the way GitHub is currently working.

**Comment by paolomainardi** [comment]
First of all, let me say that this project is great, thanks for your effort!

Just to add some thoughts here, what if the controller would act as a “fake runner” just to let GitHub to understand that a runner is available and then spawning new pods based on the actions events, this would remove the needs to always have a running pod alongside the controller, this is more or less how gitlab runners work, I don’t know if this is feasible or not, If yes I would like to help you.

**Comment by davidkarlsen** [comment]
@paolomainardi I do not think that is possible to pull of given the current apis and how GH works - but feel free to provide a working PR

**Comment by paolomainardi** [comment]
ok @davidkarlsen i'll look into it, thanks.

**Comment by paolomainardi** [comment]
Another interesting deep-dive about this topic: https://dev.to/wayofthepie/ephemeral-self-hosted-github-actions-runners-1h5m

**Comment by dudicoco** [comment]
@davidkarlsen would https://github.com/actions/runner/pull/660 make this possible?

**Comment by davidkarlsen** [comment]
> @davidkarlsen would https://github.com/actions/runner/pull/660 make this possible? 

Not really.
